### PR TITLE
Support python3

### PR DESCRIPTION
**Pull request by skudriashev**
Related to issue #5.

### CODE REVIEW

**Comment by acdha** [comment]
Thanks for picking this up. I looked at the patch but Python 2.x doesn't have a writeln() method on file objects. I think we can solve this by adding `from __future__ import print_function` at the top of the file and then using `print(…, file=stream)`.

**Comment by acdha** [comment]
fdb61a9ae45916d037ee5af247e29057c27a3d53 works on Python 3.4 in my testing, which is now easier thanks to adding a tox config file

**Comment by skudriashev** [comment]
So, shell I re-do this patch with print(file=stream)?

**Comment by skudriashev** [comment]
Oh, I see.

**Pull request closed without merging**
